apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: celery-perf

resources:
  - namespace/namespace.yaml
  - rbac/serviceaccount.yaml
  - rbac/role.yaml
  - rbac/rolebinding.yaml
  - config/configmap.yaml
  - worker/deployment.yaml
  - producer/job.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: celery-perf
